name: Cypress Tests Demo

on:
  push:
    branches:
      - master  # or 'main', depending on your default branch name
  pull_request:
    branches:
      - master  # or 'main', depending on your default branch name

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the same Node.js version as in your project

      - name: Install dependencies
        run: npm ci

      - name: Debug directory contents
        run: |
          echo "Current directory:"
          ls -la
          echo "Cypress directory:"
          ls -la cypress

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos